# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fstaff',
            old_name='user',
            new_name='staff_name',
        ),
        migrations.RenameField(
            model_name='fstaff',
            old_name='ut',
            new_name='staff_type',
        ),
    ]
